package entity;
// Generated 2017-9-25 0:32:35 by Hibernate Tools 5.2.3.Final

/**
 * DsChat generated by hbm2java
 */
public class DsChat implements java.io.Serializable {

	private int chId;
	private int chPublisherid;
	private int chReceiver;
	private int chCollegeid;
	private int chMajorid;
	private int chClassid;
	private String chTime;
	private String chContent;

	public DsChat() {
	}

	public DsChat(int chId, int chPublisherid, int chReceiver, int chCollegeid, int chMajorid, int chClassid,
			String chTime, String chContent) {
		this.chId = chId;
		this.chPublisherid = chPublisherid;
		this.chReceiver = chReceiver;
		this.chCollegeid = chCollegeid;
		this.chMajorid = chMajorid;
		this.chClassid = chClassid;
		this.chTime = chTime;
		this.chContent = chContent;
	}

	public int getChId() {
		return this.chId;
	}

	public void setChId(int chId) {
		this.chId = chId;
	}

	public int getChPublisherid() {
		return this.chPublisherid;
	}

	public void setChPublisherid(int chPublisherid) {
		this.chPublisherid = chPublisherid;
	}

	public int getChReceiver() {
		return this.chReceiver;
	}

	public void setChReceiver(int chReceiver) {
		this.chReceiver = chReceiver;
	}

	public int getChCollegeid() {
		return this.chCollegeid;
	}

	public void setChCollegeid(int chCollegeid) {
		this.chCollegeid = chCollegeid;
	}

	public int getChMajorid() {
		return this.chMajorid;
	}

	public void setChMajorid(int chMajorid) {
		this.chMajorid = chMajorid;
	}

	public int getChClassid() {
		return this.chClassid;
	}

	public void setChClassid(int chClassid) {
		this.chClassid = chClassid;
	}

	public String getChTime() {
		return this.chTime;
	}

	public void setChTime(String chTime) {
		this.chTime = chTime;
	}

	public String getChContent() {
		return this.chContent;
	}

	public void setChContent(String chContent) {
		this.chContent = chContent;
	}

}
