package entity;

import java.util.Date;

// Generated 2017-10-14 23:08:04 by Hibernate Tools 5.2.3.Final



/**
 * DsChat generated by hbm2java
 */
public class DsChat  implements java.io.Serializable {


     private int chId;
     private Integer chPublisherid;
     private Integer chReceiver;
     private Integer chCollegeid;
     private Integer chMajorid;
     private Integer chClassid;
     private long chTime;
     private String chContent;

    public DsChat() {
    }

    public DsChat(int chId, int chPublisherid, int chReceiver, int chCollegeid, int chMajorid, int chClassid, long chTime, String chContent) {
       this.chId = chId;
       this.chPublisherid = chPublisherid;
       this.chReceiver = chReceiver;
       this.chCollegeid = chCollegeid;
       this.chMajorid = chMajorid;
       this.chClassid = chClassid;
       this.chTime = chTime;
       this.chContent = chContent;
    }
   
    public int getChId() {
        return this.chId;
    }
    
    public void setChId(int chId) {
        this.chId = chId;
    }
    public Integer getChPublisherid() {
        return this.chPublisherid;
    }
    
    public void setChPublisherid(Integer chPublisherid) {
        this.chPublisherid = chPublisherid;
    }
    public Integer getChReceiver() {
        return this.chReceiver;
    }
    
    public void setChReceiver(Integer chReceiver) {
        this.chReceiver = chReceiver;
    }
    public int getChCollegeid() {
        return this.chCollegeid;
    }
    
    public void setChCollegeid(int chCollegeid) {
        this.chCollegeid = chCollegeid;
    }
    public int getChMajorid() {
        return this.chMajorid;
    }
    
    public void setChMajorid(int chMajorid) {
        this.chMajorid = chMajorid;
    }
    public int getChClassid() {
        return this.chClassid;
    }
    
    public void setChClassid(int chClassid) {
        this.chClassid = chClassid;
    }
    
    public long getChTime() {
		return chTime;
	}

	public void setChTime(long chTime) {
		this.chTime = chTime;
	}

	public String getChContent() {
        return this.chContent;
    }
    
    public void setChContent(String chContent) {
        this.chContent = chContent;
    }




}


