package entity;
// Generated 2017-9-25 0:32:35 by Hibernate Tools 5.2.3.Final

/**
 * DsCollege generated by hbm2java
 */
public class DsCollege implements java.io.Serializable {

	private Integer clId;
	private String clName;

	public DsCollege() {
	}

	public DsCollege(String clName) {
		this.clName = clName;
	}

	public Integer getClId() {
		return this.clId;
	}

	public void setClId(Integer clId) {
		this.clId = clId;
	}

	public String getClName() {
		return this.clName;
	}

	public void setClName(String clName) {
		this.clName = clName;
	}

}
