package entity;
// Generated 2017-9-25 0:32:35 by Hibernate Tools 5.2.3.Final

/**
 * DsManagerinfo generated by hbm2java
 */
public class DsManagerinfo implements java.io.Serializable {

	private Integer mgId;
	private Integer mgCollegeid;
	private Integer mgMajorid;
	private Integer mgClassid;
	private int mgReplyid;
	private Integer mgPaperid;
	private int mgPowerid;
	private String mgStuname;
	private String mgUsername;
	private String mgPassword;
	private String mgTelnumber;
	private String mgEmail;

	public DsManagerinfo() {
	}

	public DsManagerinfo(int mgReplyid, int mgPowerid, String mgStuname, String mgUsername, String mgPassword) {
		this.mgReplyid = mgReplyid;
		this.mgPowerid = mgPowerid;
		this.mgStuname = mgStuname;
		this.mgUsername = mgUsername;
		this.mgPassword = mgPassword;
	}

	public DsManagerinfo(Integer mgCollegeid, Integer mgMajorid, Integer mgClassid, int mgReplyid, Integer mgPaperid,
			int mgPowerid, String mgStuname, String mgUsername, String mgPassword, String mgTelnumber, String mgEmail) {
		this.mgCollegeid = mgCollegeid;
		this.mgMajorid = mgMajorid;
		this.mgClassid = mgClassid;
		this.mgReplyid = mgReplyid;
		this.mgPaperid = mgPaperid;
		this.mgPowerid = mgPowerid;
		this.mgStuname = mgStuname;
		this.mgUsername = mgUsername;
		this.mgPassword = mgPassword;
		this.mgTelnumber = mgTelnumber;
		this.mgEmail = mgEmail;
	}

	public Integer getMgId() {
		return this.mgId;
	}

	public void setMgId(Integer mgId) {
		this.mgId = mgId;
	}

	public Integer getMgCollegeid() {
		return this.mgCollegeid;
	}

	public void setMgCollegeid(Integer mgCollegeid) {
		this.mgCollegeid = mgCollegeid;
	}

	public Integer getMgMajorid() {
		return this.mgMajorid;
	}

	public void setMgMajorid(Integer mgMajorid) {
		this.mgMajorid = mgMajorid;
	}

	public Integer getMgClassid() {
		return this.mgClassid;
	}

	public void setMgClassid(Integer mgClassid) {
		this.mgClassid = mgClassid;
	}

	public int getMgReplyid() {
		return this.mgReplyid;
	}

	public void setMgReplyid(int mgReplyid) {
		this.mgReplyid = mgReplyid;
	}

	public Integer getMgPaperid() {
		return this.mgPaperid;
	}

	public void setMgPaperid(Integer mgPaperid) {
		this.mgPaperid = mgPaperid;
	}

	public int getMgPowerid() {
		return this.mgPowerid;
	}

	public void setMgPowerid(int mgPowerid) {
		this.mgPowerid = mgPowerid;
	}

	public String getMgStuname() {
		return this.mgStuname;
	}

	public void setMgStuname(String mgStuname) {
		this.mgStuname = mgStuname;
	}

	public String getMgUsername() {
		return this.mgUsername;
	}

	public void setMgUsername(String mgUsername) {
		this.mgUsername = mgUsername;
	}

	public String getMgPassword() {
		return this.mgPassword;
	}

	public void setMgPassword(String mgPassword) {
		this.mgPassword = mgPassword;
	}

	public String getMgTelnumber() {
		return this.mgTelnumber;
	}

	public void setMgTelnumber(String mgTelnumber) {
		this.mgTelnumber = mgTelnumber;
	}

	public String getMgEmail() {
		return this.mgEmail;
	}

	public void setMgEmail(String mgEmail) {
		this.mgEmail = mgEmail;
	}

}
