package entity;

import javax.persistence.Entity;

// Generated 2017-10-14 23:08:04 by Hibernate Tools 5.2.3.Final



/**
 * DsPower generated by hbm2java
 */
@Entity
public class DsPower  implements java.io.Serializable {


     private Integer pwId;
     private String pwUsertype;
     private String pwPagepower;
     private String pwStudentinfo;
     private String pwManagerinfo;
     private String pwSupermanager;
     private String pwSubject;
     private String pwTask;
     private String pwNotice;
     private String pwPaper;
     private String pwChat;
     private String pwApplyalloat;
     private String pwCollege;
     private String pwMajor;
     private String pwClass;
     private String pwPower;

    public DsPower() {
    }

    public DsPower(String pwUsertype, String pwPagepower, String pwStudentinfo, String pwManagerinfo, String pwSupermanager, String pwSubject, String pwTask, String pwNotice, String pwPaper, String pwChat, String pwApplyalloat, String pwCollege, String pwMajor, String pwClass, String pwPower) {
       this.pwUsertype = pwUsertype;
       this.pwPagepower = pwPagepower;
       this.pwStudentinfo = pwStudentinfo;
       this.pwManagerinfo = pwManagerinfo;
       this.pwSupermanager = pwSupermanager;
       this.pwSubject = pwSubject;
       this.pwTask = pwTask;
       this.pwNotice = pwNotice;
       this.pwPaper = pwPaper;
       this.pwChat = pwChat;
       this.pwApplyalloat = pwApplyalloat;
       this.pwCollege = pwCollege;
       this.pwMajor = pwMajor;
       this.pwClass = pwClass;
       this.pwPower = pwPower;
    }
   
    public Integer getPwId() {
        return this.pwId;
    }
    
    public void setPwId(Integer pwId) {
        this.pwId = pwId;
    }
    public String getPwUsertype() {
        return this.pwUsertype;
    }
    
    public void setPwUsertype(String pwUsertype) {
        this.pwUsertype = pwUsertype;
    }
    public String getPwPagepower() {
        return this.pwPagepower;
    }
    
    public void setPwPagepower(String pwPagepower) {
        this.pwPagepower = pwPagepower;
    }
    public String getPwStudentinfo() {
        return this.pwStudentinfo;
    }
    
    public void setPwStudentinfo(String pwStudentinfo) {
        this.pwStudentinfo = pwStudentinfo;
    }
    public String getPwManagerinfo() {
        return this.pwManagerinfo;
    }
    
    public void setPwManagerinfo(String pwManagerinfo) {
        this.pwManagerinfo = pwManagerinfo;
    }
    public String getPwSupermanager() {
        return this.pwSupermanager;
    }
    
    public void setPwSupermanager(String pwSupermanager) {
        this.pwSupermanager = pwSupermanager;
    }
    public String getPwSubject() {
        return this.pwSubject;
    }
    
    public void setPwSubject(String pwSubject) {
        this.pwSubject = pwSubject;
    }
    public String getPwTask() {
        return this.pwTask;
    }
    
    public void setPwTask(String pwTask) {
        this.pwTask = pwTask;
    }
    public String getPwNotice() {
        return this.pwNotice;
    }
    
    public void setPwNotice(String pwNotice) {
        this.pwNotice = pwNotice;
    }
    public String getPwPaper() {
        return this.pwPaper;
    }
    
    public void setPwPaper(String pwPaper) {
        this.pwPaper = pwPaper;
    }
    public String getPwChat() {
        return this.pwChat;
    }
    
    public void setPwChat(String pwChat) {
        this.pwChat = pwChat;
    }
    public String getPwApplyalloat() {
        return this.pwApplyalloat;
    }
    
    public void setPwApplyalloat(String pwApplyalloat) {
        this.pwApplyalloat = pwApplyalloat;
    }
    public String getPwCollege() {
        return this.pwCollege;
    }
    
    public void setPwCollege(String pwCollege) {
        this.pwCollege = pwCollege;
    }
    public String getPwMajor() {
        return this.pwMajor;
    }
    
    public void setPwMajor(String pwMajor) {
        this.pwMajor = pwMajor;
    }
    public String getPwClass() {
        return this.pwClass;
    }
    
    public void setPwClass(String pwClass) {
        this.pwClass = pwClass;
    }
    public String getPwPower() {
        return this.pwPower;
    }
    
    public void setPwPower(String pwPower) {
        this.pwPower = pwPower;
    }




}


