package entity;

import java.util.Date;

// Generated 2017-10-14 23:08:04 by Hibernate Tools 5.2.3.Final



/**
 * DsStudentinfo generated by hbm2java
 */
public class DsStudentinfo  implements java.io.Serializable {


     private Integer stId;
     private Integer stCollegeid;
     private Integer stMajorid;
     private Integer stClassid;
     private Integer stTeacherid;
     private Integer stPaperid;
     private Integer stSubjectid;
     private Integer stReplyid;
     private Integer stPowerid;
     private String stStuname;
     private String stUsername;
     private String stPassword;
     private String stTelnumber;
     private String stEmail;
     private Float stScore;
     private Long stLastQueryTime;
    public DsStudentinfo() {
    }

	
    public DsStudentinfo(int stCollegeid, int stMajorid, int stClassid, int stTeacherid, int stPaperid, int stReplyid, int stPowerid, String stStuname, String stUsername, String stPassword) {
        this.stCollegeid = stCollegeid;
        this.stMajorid = stMajorid;
        this.stClassid = stClassid;
        this.stTeacherid = stTeacherid;
        this.stPaperid = stPaperid;
        this.stReplyid = stReplyid;
        this.stPowerid = stPowerid;
        this.stStuname = stStuname;
        this.stUsername = stUsername;
        this.stPassword = stPassword;
    }
    public DsStudentinfo(int stCollegeid, int stMajorid, int stClassid, int stTeacherid, int stPaperid, Integer stSubjectid, int stReplyid, int stPowerid, String stStuname, String stUsername, String stPassword, String stTelnumber, String stEmail, Float stScore) {
       this.stCollegeid = stCollegeid;
       this.stMajorid = stMajorid;
       this.stClassid = stClassid;
       this.stTeacherid = stTeacherid;
       this.stPaperid = stPaperid;
       this.stSubjectid = stSubjectid;
       this.stReplyid = stReplyid;
       this.stPowerid = stPowerid;
       this.stStuname = stStuname;
       this.stUsername = stUsername;
       this.stPassword = stPassword;
       this.stTelnumber = stTelnumber;
       this.stEmail = stEmail;
       this.stScore = stScore;
    }
   
    public Integer getStId() {
        return this.stId;
    }
    
    public void setStId(Integer stId) {
        this.stId = stId;
    }
    public int getStCollegeid() {
        return this.stCollegeid;
    }
    
    public void setStCollegeid(int stCollegeid) {
        this.stCollegeid = stCollegeid;
    }
    public int getStMajorid() {
        return this.stMajorid;
    }
    
    public void setStMajorid(int stMajorid) {
        this.stMajorid = stMajorid;
    }
    public int getStClassid() {
        return this.stClassid;
    }
    
    public void setStClassid(int stClassid) {
        this.stClassid = stClassid;
    }
    public int getStTeacherid() {
        return this.stTeacherid;
    }
    
    public void setStTeacherid(int stTeacherid) {
        this.stTeacherid = stTeacherid;
    }
    public int getStPaperid() {
        return this.stPaperid;
    }
    
    public void setStPaperid(int stPaperid) {
        this.stPaperid = stPaperid;
    }
    public Integer getStSubjectid() {
        return this.stSubjectid;
    }
    
    public void setStSubjectid(Integer stSubjectid) {
        this.stSubjectid = stSubjectid;
    }
    public int getStReplyid() {
        return this.stReplyid;
    }
    
    public void setStReplyid(int stReplyid) {
        this.stReplyid = stReplyid;
    }
    public int getStPowerid() {
        return this.stPowerid;
    }
    
    public void setStPowerid(int stPowerid) {
        this.stPowerid = stPowerid;
    }
    public String getStStuname() {
        return this.stStuname;
    }
    
    public void setStStuname(String stStuname) {
        this.stStuname = stStuname;
    }
    public String getStUsername() {
        return this.stUsername;
    }
    
    public void setStUsername(String stUsername) {
        this.stUsername = stUsername;
    }
    public String getStPassword() {
        return this.stPassword;
    }
    
    public void setStPassword(String stPassword) {
        this.stPassword = stPassword;
    }
    public String getStTelnumber() {
        return this.stTelnumber;
    }
    
    public void setStTelnumber(String stTelnumber) {
        this.stTelnumber = stTelnumber;
    }
    public String getStEmail() {
        return this.stEmail;
    }
    
    public void setStEmail(String stEmail) {
        this.stEmail = stEmail;
    }
    public Float getStScore() {
        return this.stScore;
    }
    
    public void setStScore(Float stScore) {
        this.stScore = stScore;
    }


	public Long getStLastQueryTime() {
		return stLastQueryTime;
	}


	public void setStLastQueryTime(Long stLastQueryTime) {
		this.stLastQueryTime = stLastQueryTime;
	}

    


}


