package entity;


import java.util.Date;


// Generated 2017-10-14 23:08:04 by Hibernate Tools 5.2.3.Final



/**
 * DsStudentinfo generated by hbm2java
 */
public class DsStudentinfo  implements java.io.Serializable {


     private Integer stId;
     private Integer stCollegeid;
     private Integer stMajorid;
     private Integer stClassid;
     private Integer stTeacherid;
     private Integer stPaperid;
     private Integer stSubjectid;
     private Integer stReplyid;
     private Integer stPowerid;

     private String stStuname;
     private String stUsername;
     private String stPassword;
     private String stTelnumber;
     private String stEmail;
     private Float stScore;
     private Long stLastQueryTime;

	public Integer getStId() {
        return this.stId;
    }
    
    public void setStId(Integer stId) {
        this.stId = stId;
    }
    public String getStStuname() {
        return this.stStuname;
    }
    
    public void setStStuname(String stStuname) {
        this.stStuname = stStuname;
    }
    public String getStUsername() {
        return this.stUsername;
    }
    
    public void setStUsername(String stUsername) {
        this.stUsername = stUsername;
    }
    public String getStPassword() {
        return this.stPassword;
    }
    
    public void setStPassword(String stPassword) {
        this.stPassword = stPassword;
    }
    public String getStTelnumber() {
        return this.stTelnumber;
    }
    
    public void setStTelnumber(String stTelnumber) {
        this.stTelnumber = stTelnumber;
    }
    public String getStEmail() {
        return this.stEmail;
    }
    
    public void setStEmail(String stEmail) {
        this.stEmail = stEmail;
    }
    public Float getStScore() {
        return this.stScore;
    }
    
    public void setStScore(Float stScore) {
        this.stScore = stScore;
    }


	public Integer getStPowerid() {
		return stPowerid;
	}

	public void setStPowerid(Integer stPowerid) {
		this.stPowerid = stPowerid;
	}

	public Long getStLastQueryTime() {
		return stLastQueryTime;
	}


	public void setStLastQueryTime(Long stLastQueryTime) {
		this.stLastQueryTime = stLastQueryTime;
	}

	public Integer getStCollegeid() {
		return stCollegeid;
	}

	public void setStCollegeid(Integer stCollegeid) {
		this.stCollegeid = stCollegeid;
	}

	public Integer getStMajorid() {
		return stMajorid;
	}

	public void setStMajorid(Integer stMajorid) {
		this.stMajorid = stMajorid;
	}

	public Integer getStClassid() {
		return stClassid;
	}

	public void setStClassid(Integer stClassid) {
		this.stClassid = stClassid;
	}

	public Integer getStTeacherid() {
		return stTeacherid;
	}

	public void setStTeacherid(Integer stTeacherid) {
		this.stTeacherid = stTeacherid;
	}

	public Integer getStPaperid() {
		return stPaperid;
	}

	public void setStPaperid(Integer stPaperid) {
		this.stPaperid = stPaperid;
	}

	public Integer getStSubjectid() {
		return stSubjectid;
	}

	public void setStSubjectid(Integer stSubjectid) {
		this.stSubjectid = stSubjectid;
	}

	public Integer getStReplyid() {
		return stReplyid;
	}

	public void setStReplyid(Integer stReplyid) {
		this.stReplyid = stReplyid;
	}

    


}


