package entity;
// Generated 2017-9-25 0:32:35 by Hibernate Tools 5.2.3.Final

/**
 * DsSubject generated by hbm2java
 */
public class DsSubject implements java.io.Serializable {

	private Integer sbId;
	private int sbStudentid;
	private int sbTeacherid;
	private int sbCollegeid;
	private int sbMajorid;
	private String sbTitle;
	private String sbComments;
	private String sbContent;
	private String sbStatus;

	public DsSubject() {
	}

	public DsSubject(int sbStudentid, int sbTeacherid, int sbCollegeid, int sbMajorid, String sbTitle, String sbContent,
			String sbStatus) {
		this.sbStudentid = sbStudentid;
		this.sbTeacherid = sbTeacherid;
		this.sbCollegeid = sbCollegeid;
		this.sbMajorid = sbMajorid;
		this.sbTitle = sbTitle;
		this.sbContent = sbContent;
		this.sbStatus = sbStatus;
	}

	public DsSubject(int sbStudentid, int sbTeacherid, int sbCollegeid, int sbMajorid, String sbTitle,
			String sbComments, String sbContent, String sbStatus) {
		this.sbStudentid = sbStudentid;
		this.sbTeacherid = sbTeacherid;
		this.sbCollegeid = sbCollegeid;
		this.sbMajorid = sbMajorid;
		this.sbTitle = sbTitle;
		this.sbComments = sbComments;
		this.sbContent = sbContent;
		this.sbStatus = sbStatus;
	}

	public Integer getSbId() {
		return this.sbId;
	}

	public void setSbId(Integer sbId) {
		this.sbId = sbId;
	}

	public int getSbStudentid() {
		return this.sbStudentid;
	}

	public void setSbStudentid(int sbStudentid) {
		this.sbStudentid = sbStudentid;
	}

	public int getSbTeacherid() {
		return this.sbTeacherid;
	}

	public void setSbTeacherid(int sbTeacherid) {
		this.sbTeacherid = sbTeacherid;
	}

	public int getSbCollegeid() {
		return this.sbCollegeid;
	}

	public void setSbCollegeid(int sbCollegeid) {
		this.sbCollegeid = sbCollegeid;
	}

	public int getSbMajorid() {
		return this.sbMajorid;
	}

	public void setSbMajorid(int sbMajorid) {
		this.sbMajorid = sbMajorid;
	}

	public String getSbTitle() {
		return this.sbTitle;
	}

	public void setSbTitle(String sbTitle) {
		this.sbTitle = sbTitle;
	}

	public String getSbComments() {
		return this.sbComments;
	}

	public void setSbComments(String sbComments) {
		this.sbComments = sbComments;
	}

	public String getSbContent() {
		return this.sbContent;
	}

	public void setSbContent(String sbContent) {
		this.sbContent = sbContent;
	}

	public String getSbStatus() {
		return this.sbStatus;
	}

	public void setSbStatus(String sbStatus) {
		this.sbStatus = sbStatus;
	}

}
