package entity;
// Generated 2017-10-14 23:08:04 by Hibernate Tools 5.2.3.Final



/**
 * DsSubject generated by hbm2java
 */
public class DsSubject  implements java.io.Serializable {


     private Integer sbId;
     private Integer sbStudentid;
     private Integer sbTeacherid;
     private Integer sbCollegeid;
     private Integer sbMajorid;
     private String sbTitle;
     private String sbStatus;
     private String sbType;
     private String sbComments;
     private String sbContent;

    public DsSubject() {
    }

	
    public DsSubject(int sbStudentid, int sbTeacherid, int sbCollegeid, int sbMajorid, String sbTitle, String sbStatus, String sbType, String sbContent) {
        this.sbStudentid = sbStudentid;
        this.sbTeacherid = sbTeacherid;
        this.sbCollegeid = sbCollegeid;
        this.sbMajorid = sbMajorid;
        this.sbTitle = sbTitle;
        this.sbStatus = sbStatus;
        this.sbType = sbType;
        this.sbContent = sbContent;
    }
    public DsSubject(int sbStudentid, int sbTeacherid, int sbCollegeid, int sbMajorid, String sbTitle, String sbStatus, String sbType, String sbComments, String sbContent) {
       this.sbStudentid = sbStudentid;
       this.sbTeacherid = sbTeacherid;
       this.sbCollegeid = sbCollegeid;
       this.sbMajorid = sbMajorid;
       this.sbTitle = sbTitle;
       this.sbStatus = sbStatus;
       this.sbType = sbType;
       this.sbComments = sbComments;
       this.sbContent = sbContent;
    }
   
    public Integer getSbId() {
        return this.sbId;
    }
    
    public void setSbId(Integer sbId) {
        this.sbId = sbId;
    }
    public Integer getSbStudentid() {
        return this.sbStudentid;
    }
    
    public void setSbStudentid(Integer sbStudentid) {
        this.sbStudentid = sbStudentid;
    }
    public int getSbTeacherid() {
        return this.sbTeacherid;
    }
    
    public void setSbTeacherid(Integer sbTeacherid) {
        this.sbTeacherid = sbTeacherid;
    }
    public int getSbCollegeid() {
        return this.sbCollegeid;
    }
    
    public void setSbCollegeid(Integer sbCollegeid) {
        this.sbCollegeid = sbCollegeid;
    }
    public int getSbMajorid() {
        return this.sbMajorid;
    }
    
    public void setSbMajorid(Integer sbMajorid) {
        this.sbMajorid = sbMajorid;
    }
    public String getSbTitle() {
        return this.sbTitle;
    }
    
    public void setSbTitle(String sbTitle) {
        this.sbTitle = sbTitle;
    }
    public String getSbStatus() {
        return this.sbStatus;
    }
    
    public void setSbStatus(String sbStatus) {
        this.sbStatus = sbStatus;
    }
    public String getSbType() {
        return this.sbType;
    }
    
    public void setSbType(String sbType) {
        this.sbType = sbType;
    }
    public String getSbComments() {
        return this.sbComments;
    }
    
    public void setSbComments(String sbComments) {
        this.sbComments = sbComments;
    }
    public String getSbContent() {
        return this.sbContent;
    }
    
    public void setSbContent(String sbContent) {
        this.sbContent = sbContent;
    }




}


