package entity;
// Generated 2017-10-14 23:08:04 by Hibernate Tools 5.2.3.Final



/**
 * DsSubject generated by hbm2java
 */
public class DsSubject  implements java.io.Serializable {


     private Integer sbId;
     private DsStudentinfo student;
     private DsManagerinfo teacher;
     private DsCollege college;
     private DsMajor major;
     private String sbTitle;
     private String sbStatus;
     private String sbType;
     private String sbComments;
     private String sbContent;

    public DsSubject() {
    }

	
   
   
    public Integer getSbId() {
        return this.sbId;
    }
    
    public void setSbId(Integer sbId) {
        this.sbId = sbId;
    }
    
    public DsStudentinfo getStudent() {
		return student;
	}


	public void setStudent(DsStudentinfo student) {
		this.student = student;
	}


	
    public DsManagerinfo getTeacher() {
		return teacher;
	}




	public void setTeacher(DsManagerinfo teacher) {
		this.teacher = teacher;
	}




	public DsCollege getCollege() {
		return college;
	}




	public void setCollege(DsCollege college) {
		this.college = college;
	}




	public DsMajor getMajor() {
		return major;
	}




	public void setMajor(DsMajor major) {
		this.major = major;
	}




	public String getSbTitle() {
        return this.sbTitle;
    }
    
    public void setSbTitle(String sbTitle) {
        this.sbTitle = sbTitle;
    }
    public String getSbStatus() {
        return this.sbStatus;
    }
    
    public void setSbStatus(String sbStatus) {
        this.sbStatus = sbStatus;
    }
    public String getSbType() {
        return this.sbType;
    }
    
    public void setSbType(String sbType) {
        this.sbType = sbType;
    }
    public String getSbComments() {
        return this.sbComments;
    }
    
    public void setSbComments(String sbComments) {
        this.sbComments = sbComments;
    }
    public String getSbContent() {
        return this.sbContent;
    }
    
    public void setSbContent(String sbContent) {
        this.sbContent = sbContent;
    }




}


