package entity;
// Generated 2017-10-14 23:08:04 by Hibernate Tools 5.2.3.Final



/**
 * DsSupermanager generated by hbm2java
 */
public class DsSupermanager  implements java.io.Serializable {


     private Integer smgId;
     private int smgPowerid;
     private String smgStuname;
     private String smgUsername;
     private String smgPassword;

    public DsSupermanager() {
    }

    public DsSupermanager(int smgPowerid, String smgStuname, String smgUsername, String smgPassword) {
       this.smgPowerid = smgPowerid;
       this.smgStuname = smgStuname;
       this.smgUsername = smgUsername;
       this.smgPassword = smgPassword;
    }
   
    public Integer getSmgId() {
        return this.smgId;
    }
    
    public void setSmgId(Integer smgId) {
        this.smgId = smgId;
    }
    public int getSmgPowerid() {
        return this.smgPowerid;
    }
    
    public void setSmgPowerid(int smgPowerid) {
        this.smgPowerid = smgPowerid;
    }
    public String getSmgStuname() {
        return this.smgStuname;
    }
    
    public void setSmgStuname(String smgStuname) {
        this.smgStuname = smgStuname;
    }
    public String getSmgUsername() {
        return this.smgUsername;
    }
    
    public void setSmgUsername(String smgUsername) {
        this.smgUsername = smgUsername;
    }
    public String getSmgPassword() {
        return this.smgPassword;
    }
    
    public void setSmgPassword(String smgPassword) {
        this.smgPassword = smgPassword;
    }




}


